# Generated by Django 5.1.5 on 2025-02-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='backup',
            name='name',
            field=models.CharField(default='Untitled Backup', max_length=255),
        ),
        migrations.AddField(
            model_name='backup',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('failed', 'Failed')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='backup',
            name='type',
            field=models.CharField(choices=[('full', 'Full'), ('partial', 'Partial')], default='full', max_length=10),
        ),
    ]
