# Generated by Django 5.1.4 on 2024-12-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_status_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='active_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='completion_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='members_count',
            field=models.IntegerField(default=0),
        ),
    ]
