# Generated by Django 5.1.4 on 2024-12-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='api_allowed_ips',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='api_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='api_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='api_rate_limit',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auto_backup_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='backup_frequency_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='backup_location',
            field=models.CharField(default='backups/', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='backup_retention_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='last_backup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_server',
            field=models.CharField(default='smtp.example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
