# Generated by Django 5.1.4 on 2025-01-23 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='department',
            name='active_projects',
        ),
        migrations.RemoveField(
            model_name='department',
            name='completed_projects',
        ),
        migrations.RemoveField(
            model_name='department',
            name='completion_rate',
        ),
        migrations.RemoveField(
            model_name='department',
            name='members_count',
        ),
        migrations.RemoveField(
            model_name='department',
            name='total_members',
        ),
        migrations.AddField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
