# Generated by Django 5.1.4 on 2025-01-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='active_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='completion_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
