# Generated by Django 5.1.4 on 2025-01-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_department_active_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='weather_api_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='weather_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
